In [1]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(salary_list):
        if len(salary_list) == 0:
            return 0
        return sum(salary_list) / len(salary_list)


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


# Creating instances of Employee and FulltimeEmployee classes
employee1 = Employee("Jimmy Carter", "Carter", 40000, "Human Resources")
employee2 = Employee("Ryan Gosling", "Gosling", 60000, "Finance")

fulltime_employee1 = FulltimeEmployee("Tom Hanks", "Hanks", 70000, "Marketing")
fulltime_employee2 = FulltimeEmployee("Bobby Brown", "Brown", 80000, "Engineering")

# Calling member functions
print("Number of employees:", Employee.num_employees)

salaries = [employee1.salary, employee2.salary, fulltime_employee1.salary, fulltime_employee2.salary]
print("Average salary:", Employee.average_salary(salaries))


Number of employees: 4
Average salary: 62500.0


In [5]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 along axis=1
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print(reshaped_array)

[[ 3.82742505  0.         17.61506028  5.21816866  6.57518762]
 [ 5.72294301  4.08979337  0.         12.8257235   9.54239631]
 [ 2.91408116  3.1310031   0.          5.82377181  1.07556005]
 [ 0.          2.33555267  9.64495385 14.15770628  2.23730037]]
